format_version: 4
pipelines:
  "prm-mesh-aws-forwarder.audit":
    group: shared-components-audit
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    timer:
      spec: 0 0 8 ? * MON,TUE,WED,THU,FRI *
    stages:
      - audit:
          clean_workspace: true
          jobs:
            dependency_check:
              resources:
                - docker
              artifacts:
                - build:
                    source: audit-output.txt
                    destination: reports
              tabs:
                dependency: reports/audit-output.txt
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-dep