format_version: 4
pipelines:
  "prm-mesh-aws-forwarder":
    group: shared-components
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test_inbox_forwarder:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate
      - build_inbox_forwarder:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - IMAGE_TAG=$GO_PIPELINE_LABEL ./tasks publish-docker
