format_version: 4
pipelines:
  "prm-gp2gp-docker-mi-data-uploader":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test_inbox_forwarder:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: mesh-inbox-s3-forwarder
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate
      - test_file_forwarder:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: mesh-file-s3-forwarder
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate
      - build_file_forwarder:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: mesh-file-s3-forwarder
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build-docker
